---
- name: Configure Servers
  hosts: deploy
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
          - nginx
        state: present

    - name: Create a virtual environment for Python
      command:
        cmd: python3 -m venv /home/{{ ansible_user }}/flaskenv
        creates: /home/{{ ansible_user }}/flaskenv

    - name: Install pip packages globally
      pip:
        name:
          - pip
          - wheel
        state: latest

    - name: Ensure Nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: yes
