---
- name: Configure Servers
  hosts: deploy
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
          - nginx
        state: present

    - name: Create a virtual environment for Python
      command:
        cmd: python3 -m venv /home/{{ ansible_user }}/flaskenv
        creates: /home/{{ ansible_user }}/flaskenv

    - name: Upgrade pip and wheel in virtual environment
      command:
        cmd: /home/{{ ansible_user }}/flaskenv/bin/python -m pip install --upgrade pip wheel
        creates: /home/{{ ansible_user }}/flaskenv/bin/pip

    - name: Install pip packages from requirements.txt in virtual environment
      pip:
        requirements: /home/{{ ansible_user }}/path/to/requirements.txt
        virtualenv: /home/{{ ansible_user }}/flaskenv
        state: present

    - name: Ensure Nginx is enabled and started
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
