---
- name: Configure Servers
  hosts: deploy
  become: yes

  vars:
    app_dir: /home/ubuntu/flask-app
    git_hub_repo: https://github.com/timothy-toweh/flask-app-project.git 

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install essential packages
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
          - git
          - nginx
        state: present

    - name: Remove existing flask-app
      file:
        path: "{{ app_dir }}"
        state: absent
      ignore_errors: yes

    - name: Create flask directory for Ubuntu
      file:
        path: "{{ app_dir }}"
        state: directory
        mode: '0777'
        owner: ubuntu
        group: ubuntu

    - name: Clone git repository
      git: 
        repo: "{{ git_hub_repo }}"
        dest: "{{ app_dir }}/"
        version: main

    - name: Create virtual environment (Ubuntu)
      command: python3 -m venv {{ app_dir }}/.myenv
      args:
        chdir: "{{ app_dir }}"

    - name: Install Flask using pip (Ubuntu)
      pip:
        name: flask
        executable: "{{ app_dir }}/.myenv/bin/pip"
        state: present