---
- name: Run Flask app
  hosts: deploy
  become: true
  vars:
    app_dir: /home/ubuntu/flask-app
  tasks:
    - name: run flask app
      command: "{{ app_dir }}/venv/bin/python {{ app_dir }}/repository/app.py &"
      async: 60
      poll: 0
